# f=open('c2.txt','x')
# print(f.name)
# print(f.mode)
# print(f.writable())
# print(f.readable())
# print(f.closed)
# print(f.encoding)

# f=open('w1.txt','w')
# print(f.name)
# print(f.mode)
# print(f.writable())
# print(f.readable())
# print(f.closed)
# print(f.encoding)

# f=open('a1.txt','a')
# print(f.name)
# print(f.mode)
# print(f.writable())
# print(f.readable())
# print(f.closed)
# print(f.encoding)

f=open('a1.txt','r')
print(f.name)
print(f.mode)
print(f.writable())
print(f.readable())
print(f.closed)
print(f.encoding)